version: "3.8"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - cluster.name=elasticsearch # Settings to start Elasticsearch in a single-node development environment
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - searchengine-network
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - searchengine-network
    depends_on: 
      - elasticsearch

volumes: # The volumes will store the database data; kept even after the containers are deleted
  elastic-data:
    driver: local

networks:
    searchengine-network:
        driver: bridge
